apiVersion: v1
kind: Service
metadata:
  name: {{ include "devpi.fullname" . }}-service
  labels:
    app: {{ include "devpi.fullname" . }}-label
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: {{ .Values.service.portName }}
  selector:
    app: {{ include "devpi.fullname" . }}-label
