replicaCount: 1

image:
  repository: asindark/devpi
  tag: 1.0.0
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3141
  portName: http

persistence:
  storageClass: "local-path"
  accessMode: ReadWriteOnce
  size: 5Gi

resources: {}
# resources:
#   requests:
#     cpu: 0
#     memory: 0
#   limits:
#     cpu: 1500m
#     memory: 3072Mi

ingress:
  enabled: true
  ingressClassName: traefik
  host: devpi.local
  path: /
  tls:
    enabled: true
    secretName: devpi-tls
    create: false  

secret:
  name: devpi-pwd
  key: password         

nodeSelector: {}
tolerations: []
affinity: {}